LANG = {
    "ja": {
        "name": "日本語",
        "font": ("Yu Gothic UI", "Meiryo UI", "MS UI Gothic"),
        "drop_audio": "ドロップ、またはクリックして選択 [wav / mp3]",
        "advanced": "詳細設定",
        "mouth": "口の開き具合",
        "lead": "タイミング補正（先行フレーム）",
        "shapes": "各フレームの最大開口種類数",
        "interval": "出力FPS",
        "eye": "目のアニメーション（自動）",
        "vowel_names": ["あ", "い", "う", "え", "お", "ん"],
        "idle": "待機中",
        "audio_required": "WAVまたはMP3を選択してください",
        "model_missing": "モデルがありません",
        "analysing": "解析中",
        "writing": "書き出し中",
        "done": "変換完了",
        "tab_convert": "変換",
        "tab_setup": "依存関係",
        "col_package": "パッケージ",
        "col_version": "バージョン",
        "col_state": "状態",
        "state_missing": "未導入",
        "state_installed": "導入済",
        "install": "インストール",
        "uninstall": "アンインストール",
    },
    "zh": {
        "name": "中文",
        "font": ("Microsoft YaHei UI", "Microsoft YaHei", "SimSun"),
        "drop_audio": "拖放，或点击选择 [wav / mp3]",
        "advanced": "高级设置",
        "mouth": "口的张开程度",
        "lead": "时机补偿（提前帧数）",
        "shapes": "每帧最大口形种类数",
        "interval": "输出FPS",
        "eye": "眼部动画（自动）",
        "vowel_names": ["A", "I", "U", "E", "O", "N"],
        "idle": "待机中",
        "audio_required": "请选择 WAV 或 MP3",
        "model_missing": "没有模型",
        "analysing": "分析中",
        "writing": "写出中",
        "done": "转换完成",
        "tab_convert": "转换",
        "tab_setup": "依赖关系",
        "col_package": "软件包",
        "col_version": "版本",
        "col_state": "状态",
        "state_missing": "未安装",
        "state_installed": "已安装",
        "install": "安装",
        "uninstall": "卸载",
    },
    "en": {
        "name": "English",
        "font": ("Segoe UI", "Tahoma", "Arial"),
        "drop_audio": "Drop, or click to select [wav / mp3]",
        "advanced": "Advanced Settings",
        "mouth": "Mouth Openness",
        "lead": "Timing Offset (Lead Frames)",
        "shapes": "Max Shape Types per Frame",
        "interval": "Output FPS",
        "eye": "Eye Animation (Auto)",
        "vowel_names": ["A", "I", "U", "E", "O", "N"],
        "idle": "Standby",
        "audio_required": "Select a WAV or MP3 file",
        "model_missing": "Model not found",
        "analysing": "Analysing",
        "writing": "Writing",
        "done": "Conversion complete",
        "tab_convert": "Convert",
        "tab_setup": "Dependencies",
        "col_package": "Package",
        "col_version": "Version",
        "col_state": "State",
        "state_missing": "Missing",
        "state_installed": "Installed",
        "install": "Install",
        "uninstall": "Uninstall",
    },
}
